server {
  listen 80;
  server_name _;

  location /api/ {
    proxy_pass http://api:8000/api/;
  }

  location /debug/ {
    proxy_pass http://api:8000/debug/;
  }

  location = /metrics {
    proxy_pass http://api:8000/metrics;
  }

  location = /health {
    proxy_pass http://api:8000/health;
  }

  location / {
    root /usr/share/nginx/html;
    try_files $uri $uri/ /index.html;
  }
}
